"""updates model

Revision ID: 6eab5a055018
Revises: e4b85e152dab
Create Date: 2020-11-02 22:02:54.443867

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6eab5a055018'
down_revision = 'e4b85e152dab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('writers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('writer_name', sa.String(length=255), nullable=True),
    sa.Column('writer_email', sa.String(length=255), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('bio', sa.String(length=255), nullable=True),
    sa.Column('profile_pic_path', sa.String(), nullable=True),
    sa.Column('writer_pass_secure', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_writers_writer_email'), 'writers', ['writer_email'], unique=True)
    op.create_index(op.f('ix_writers_writer_name'), 'writers', ['writer_name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_writers_writer_name'), table_name='writers')
    op.drop_index(op.f('ix_writers_writer_email'), table_name='writers')
    op.drop_table('writers')
    # ### end Alembic commands ###
